name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Run Qodana scan
      uses: JetBrains/qodana-action@v2022.3.2
      env:
        QODANA_API_TOKEN: ${{ secrets.QODANA_SECRET }}
      with:
        args: scan --python-interpreter python